### ISSUE TITLE
about predict.py and evl_yab.py

### ISSUE THREAD

**Issue by zhuyazhi** [wenbowen123/iros20-6d-pose-tracking#16]
1. 您好，请问predict.py和evl_yab.py这两个.py都需要运行才是测试吗？
如果要进行测试，需要运行两个.py吗?

**Comment by zhuyazhi** [comment]
我按照顺序先运行predict.py，但是出现以下error(我猜测是因为不能可视化)
Using vispy renderer
Traceback (most recent call last):
  File "predict.py", line 645, in <module>
    predictSequenceMyData()
  File "predict.py", line 566, in predictSequenceMyData
    tracker = Tracker(dataset_info, images_mean, images_std,ckpt_dir, trans_normalizer=0.03, rot_normalizer=30*np.pi/180)
  File "predict.py", line 163, in __init__
    self.renderer = VispyRenderer(dataset_info['models'][0]['model_path'], self.K, H=dataset_info['resolution'], W=dataset_info['resolution'])
  File "/opt/tiger/zyz_6d_pose/iros20-6d-pose-tracking/vispy_renderer.py", line 50, in __init__
    app.Canvas.__init__(self, show=False, size=(W,H))
  File "/home/tiger/anaconda3/envs/se3/lib/python3.7/site-packages/vispy/app/canvas.py", line 205, in __init__
    self.create_native()
  File "/home/tiger/anaconda3/envs/se3/lib/python3.7/site-packages/vispy/app/canvas.py", line 222, in create_native
    self._app.backend_module.CanvasBackend(self, **self._backend_kwargs)
  File "/home/tiger/anaconda3/envs/se3/lib/python3.7/site-packages/vispy/app/backends/_pyglet.py", line 211, in __init__
    screen=self._vispy_screen)
  File "/home/tiger/anaconda3/envs/se3/lib/python3.7/site-packages/pyglet/window/xlib/__init__.py", line 165, in __init__
    super(XlibWindow, self).__init__(*args, **kwargs)
  File "/home/tiger/anaconda3/envs/se3/lib/python3.7/site-packages/pyglet/window/__init__.py", line 570, in __init__
    display = pyglet.canvas.get_display()
  File "/home/tiger/anaconda3/envs/se3/lib/python3.7/site-packages/pyglet/canvas/__init__.py", line 94, in get_display
    return Display()
  File "/home/tiger/anaconda3/envs/se3/lib/python3.7/site-packages/pyglet/canvas/xlib.py", line 123, in __init__
    raise NoSuchDisplayException('Cannot connect to "%s"' % name)
pyglet.canvas.xlib.NoSuchDisplayException: Cannot connect to "None"
但是我注释了vispy_renderer.py中的几行之后这个错误没有了

出现了以下错误，您可以给我给一些指导吗。
<img width="1028" alt="截屏2021-01-09 下午12 38 13" src="https://user-images.githubusercontent.com/48109799/104083175-8b80ec00-5277-11eb-9232-68ce27aedf61.png">

**Comment by zhuyazhi** [comment]
我按照顺序先运行predict.py，但是出现以下error(我猜测是因为不能可视化)
Using vispy renderer
Traceback (most recent call last):
File "predict.py", line 645, in
predictSequenceMyData()
File "predict.py", line 566, in predictSequenceMyData
tracker = Tracker(dataset_info, images_mean, images_std,ckpt_dir, trans_normalizer=0.03, rot_normalizer=30*np.pi/180)
File "predict.py", line 163, in init
self.renderer = VispyRenderer(dataset_info['models'][0]['model_path'], self.K, H=dataset_info['resolution'], W=dataset_info['resolution'])
File "/opt/tiger/zyz_6d_pose/iros20-6d-pose-tracking/vispy_renderer.py", line 50, in init
app.Canvas.init(self, show=False, size=(W,H))
File "/home/tiger/anaconda3/envs/se3/lib/python3.7/site-packages/vispy/app/canvas.py", line 205, in init
self.create_native()
File "/home/tiger/anaconda3/envs/se3/lib/python3.7/site-packages/vispy/app/canvas.py", line 222, in create_native
self._app.backend_module.CanvasBackend(self, **self._backend_kwargs)
File "/home/tiger/anaconda3/envs/se3/lib/python3.7/site-packages/vispy/app/backends/_pyglet.py", line 211, in init
screen=self._vispy_screen)
File "/home/tiger/anaconda3/envs/se3/lib/python3.7/site-packages/pyglet/window/xlib/init.py", line 165, in init
super(XlibWindow, self).init(*args, **kwargs)
File "/home/tiger/anaconda3/envs/se3/lib/python3.7/site-packages/pyglet/window/init.py", line 570, in init
display = pyglet.canvas.get_display()
File "/home/tiger/anaconda3/envs/se3/lib/python3.7/site-packages/pyglet/canvas/init.py", line 94, in get_display
return Display()
File "/home/tiger/anaconda3/envs/se3/lib/python3.7/site-packages/pyglet/canvas/xlib.py", line 123, in init
raise NoSuchDisplayException('Cannot connect to "%s"' % name)
pyglet.canvas.xlib.NoSuchDisplayException: Cannot connect to "None"
但是我注释了vispy_renderer.py中的几行之后这个错误没有了

出现了以下错误，您可以给我给一些指导吗。
(se3) <Trial 1924760 worker_0> iros20-6d-pose-tracking $ python predict.py
ckpt_dir: /opt/tiger/zyz_6d_pose/iros20-6d-pose-tracking/output/YCB_weights/bleach_cleanser/model_best_val.pth.tar
dataset_info_path /opt/tiger/zyz_6d_pose/iros20-6d-pose-tracking/media/YCB_traindata/bleach_cleanser/train_data_blender_DR/../dataset_info.yml
/opt/tiger/zyz_6d_pose/iros20-6d-pose-tracking/media/YCB_Video_Dataset/models/021_bleach_cleanser/textured.ply
[  29.86251    30.459349   28.622227 1591.2026    170.07364   160.50923
  146.59778   190.98444 ]
[  29.86251    30.459349   28.622227 1591.2026    170.07364   160.50923
  146.59778   190.98444 ]
/media/YCBInEOAT_Dataset/bleach0
self.object_cloud loaded and downsampled
self.object_width= 285.37860394994397
Loading ckpt from  /opt/tiger/zyz_6d_pose/iros20-6d-pose-tracking/output/YCB_weights/bleach_cleanser/model_best_val.pth.tar
pose track ckpt epoch=112
Using vispy renderer
model_path:  /opt/tiger/zyz_6d_pose/iros20-6d-pose-tracking/media/YCB_Video_Dataset/models/021_bleach_cleanser/textured.ply
self.cam_K:
 [[1.066778e+03 0.000000e+00 3.129869e+02]
 [0.000000e+00 1.067487e+03 2.413109e+02]
 [0.000000e+00 0.000000e+00 1.000000e+00]]
making dataset... for eval
#dataset: 0
self.trans_normalizer=0.03, self.rot_normalizer=0.5235987755982988
Traceback (most recent call last):
  File "predict.py", line 645, in <module>
    predictSequenceMyData()
  File "predict.py", line 573, in predictSequenceMyData
    pred_poses = [gt_poses[0]]
IndexError: list index out of range

**Comment by zhuyazhi** [comment]
上面的问题是不是出在在两个数据集搞混了呢？
在predict.py中我该怎么选择在哪个数据集上测试

**Comment by zhuyazhi** [comment]
我改成predictSequenceYcb()，也出现了类似的error:
(se3) <Trial 1924760 worker_0> iros20-6d-pose-tracking $ python predict.py
ckpt_dir: /opt/tiger/zyz_6d_pose/iros20-6d-pose-tracking/output/YCB_weights/bleach_cleanser/model_best_val.pth.tar
dataset_info_path /opt/tiger/zyz_6d_pose/iros20-6d-pose-tracking/media/YCB_traindata/bleach_cleanser/train_data_blender_DR/../dataset_info.yml
/opt/tiger/zyz_6d_pose/iros20-6d-pose-tracking/media/YCB_Video_Dataset/models/021_bleach_cleanser/textured.ply
[  29.86251    30.459349   28.622227 1591.2026    170.07364   160.50923
  146.59778   190.98444 ]
[  29.86251    30.459349   28.622227 1591.2026    170.07364   160.50923
  146.59778   190.98444 ]
self.object_cloud loaded and downsampled
self.object_width= 285.37860394994397
Loading ckpt from  /opt/tiger/zyz_6d_pose/iros20-6d-pose-tracking/output/YCB_weights/bleach_cleanser/model_best_val.pth.tar
pose track ckpt epoch=112
Using vispy renderer
model_path:  /opt/tiger/zyz_6d_pose/iros20-6d-pose-tracking/media/YCB_Video_Dataset/models/021_bleach_cleanser/textured.ply
self.cam_K:
 [[1.066778e+03 0.000000e+00 3.129869e+02]
 [0.000000e+00 1.067487e+03 2.413109e+02]
 [0.000000e+00 0.000000e+00 1.000000e+00]]
making dataset... for eval
#dataset: 0
self.trans_normalizer=0.03, self.rot_normalizer=0.08726646259971647
Traceback (most recent call last):
  File "predict.py", line 643, in <module>
    predictSequenceYcb()
  File "predict.py", line 455, in predictSequenceYcb
    print('gt_poses[0]=\n',gt_poses[start_frame])
IndexError: list index out of range

**Comment by wenbowen123** [comment]
Hi, predict.py is used to predict pose results. eval_ycb.py will then evaluate its saved poses and get the scores on the benchmark.

**Comment by zhuyazhi** [comment]
thank you`
1. 我运行predict.py的结果是adi_auc =97.87，但是运行eval_ycb.py的结果是
add: 97.22709481181084
adi: 97.83757093086494
这两个adi有什么关系呢？
2. 我发现在eval_ycb.py中，以下代码是用于读取pred_pose的，但是默认的输出是00000.txt和00000gt.txt在一个路径下，所以len(pose_files) = 4016 。而我将pred_txt与gt_txt分别存储在out_dir/pred/和out_dir/gt/下，所以pose_files应该只读取pred_pose（00000.txt ... 02007.txt），您认为这样是对的吗？

def eval_one_class(args):
      pose_files = sorted(glob.glob(args.res_dir+'pred/'+'*.txt',recursive=True))
      print(len(pose_files))  #2008

3. 我注意到并不是所有的pred_pose和对应的gt_pose加入add计算，而是在关键帧里面的才计算，请问我的理解对吗？为什么要这样呢？

    seq_frame_str = '%04d/%06d'%(seq_id,frame_id)
    #print(seq_frame_str)
    if seq_frame_str not in keyframes:
      continue
    pred = np.loadtxt(pose_file)
    gt_file = '{}/data_organized/%04d/pose_gt/{}/%06d.txt'.format(args.ycb_dir,args.class_id)%(seq_id,frame_id)
    #print(gt_file)

我注释了这两句判断，最终的结果如下：
#if seq_frame_str not in keyframes:
      #continue
>>>>>>>>>>>>>>>> args.class_id: 12 021_bleach_cleanser
add: 97.36765553284819
adi: 97.88892223750305
希望得到您回复

**Comment by zhuyazhi** [comment]
Run evl_ycb.py，I think seq_id can be directly = 51，and seq_id = int(pose_file.replace(args.res_dir,'').split('/') [0].replace('seq','')) got an error，I think this error is related to your path， so I let seq_id = 51 directly， and got a result 
>>>>>>>>>>>>>>>> args.class_id: 12 021_bleach_cleanser
add: 93.42925158905837
adi: 97.0202518718414
Is that right? expect your reply~

the code in evl_ycb.py I modified：
  for i in range(len(pose_files)):
    pose_file = pose_files[i]
    seq_id = 51   #int(pose_file.replace(args.res_dir,'').split('/')[0].replace('seq',''))
    frame_id = int(os.path.basename(pose_file).split('.')[0][:-2])+1
    print(frame_id)
    seq_frame_str = '%04d/%06d'%(seq_id,frame_id)
    if seq_frame_str not in keyframes:
      continue
    pred = np.loadtxt(pose_file)
    gt_file = '{}/data_organized/%04d/pose_gt/{}/%06d.txt'.format(args.ycb_dir,args.class_id)%(seq_id,frame_id)
    gt_pose = np.loadtxt(gt_file)

**Comment by johnbhlm** [comment]
I think that different CAD models lead to different results.
In predict.py file, you may be using YCB_traindata->data_info.yml->textured.ply as CAD model，but in eval_ycb.py，you may be using *points.xyz as CAD model. So when calculating ADD and ADD-S will be different.

**Comment by zhuyazhi** [comment]
thank you for your suggestion~

**Comment by wenbowen123** [comment]
@johnbhlm  says is correct.

@zhuyazhi , evaluating only on keyframes is the rule of YCB-Video benchmark. You can check PoseCNN for more details on the evaluation protocol.

**Comment by zhuyazhi** [comment]
ok, thanks for your reply。

**Comment by jinzhiyang1** [comment]
> ok, thanks for your reply。
大佬你好，我最近也在看这个项目，但是在eval的时候出现了一些错误，你能分享一下eval_ycbineoat.py的配置路径么，万分感谢
