### ISSUE TITLE
about produce_train_pair_data.py

### ISSUE THREAD

**Issue by zhuyazhi** [wenbowen123/iros20-6d-pose-tracking#19]
thank you for share this code, i have some questions as below:
1. I use my own model and rgb_files generated by blender to generate image pairs, how to set class_id ?
2. and I didn't get any generated images rgbA。
/opt/tiger/zyz_6d_pose/iros20-6d-pose tracking/media/YCB_traindata/ggl/blender_syn_sequence/mydataset_DR/0000499rgb.png
[[-1.34358856e-07 -1.00000012e+00 -1.87169619e-23  5.90973608e-02]
 [ 1.00000012e+00  1.34358856e-07 -1.57009270e-16  2.34215427e-02]
 [ 1.57009270e-16 -1.87169619e-23  1.00000024e+00  5.00000238e-01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
[[ 0.05048425 -0.99854613 -0.01889992  0.16632858]
 [ 0.99428245  0.0520339  -0.09324765 -0.33160405]
 [ 0.09409552 -0.01408432  0.99546378 -2.42301163]
 [ 0.          0.          0.          1.        ]]
moving to val: 0/500
Traceback (most recent call last):
  File "produce_train_pair_data.py", line 263, in <module>
    completeBlenderYcbDR()
  File "produce_train_pair_data.py", line 253, in completeBlenderYcbDR
    shutil.move(rgbA_files[i],out_val_path+'%07drgbA.png'%(i))
IndexError: list index out of range

thank you so much.

**Comment by wenbowen123** [comment]
1. You can refer to codebases such as BlenderProc about how to get semantic labels.
2. Dont have any clue on this. Perhaps try print and debug your paths.
