### ISSUE TITLE
about B_in_camera

### ISSUE THREAD

**Issue by zhuyazhi** [wenbowen123/iros20-6d-pose-tracking#21]
hello, I am sorry to bother you again, because I have two questions that need your correction.

1. my syn_data is generated by blender, and  the pose for *B is save as a pkl(e.g.,0.pkl)，so I directly extract the pose of .pkl as *B's pose(B_in_cam)，I don't have the transformation as your code(blendercam_in_world, poses_in_world....). 
do you think this is right?
meta = np.load(rgb_file.replace('rgb.png','poses_in_world.npz'))
class_ids = meta['class_ids']
poses_in_world = meta['poses_in_world']
blendercam_in_world = meta['blendercam_in_world']
pos = np.where(class_ids==class_id)
B_in_cam = np.linalg.inv(cvcam_in_blendercam).dot(np.linalg.inv(blendercam_in_world).dot(poses_in_world[pos,:,:].reshape(4,4)))

that's my modified code:
B_in_cam = pickle.load(open('.../{:07}RT.pkl')) 

2. After generating image pairs for training， I run train.py and got an error about generating labels for training. could you tell give me some advice?

Traceback (most recent call last):
  File "train.py", line 110, in <module>
    for i, (data, target, A_in_cams, B_in_cams, rgbA, rgbB, maskA, maskB) in enumerate(train_loader):
  File "/home/tiger/anaconda3/envs/se3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 582, in __next__
    return self._process_next_batch(batch)
  File "/home/tiger/anaconda3/envs/se3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 608, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
AssertionError: Traceback (most recent call last):
  File "/home/tiger/anaconda3/envs/se3/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 99, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/tiger/anaconda3/envs/se3/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 99, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/opt/tiger/zyz_6d_pose/iros20-6d-pose-tracking/datasets.py", line 107, in __getitem__
    data, target, rgbA, rgbB, maskA, maskB = self.processData(rgbA,depthA,A_in_cam,rgbB,depthB,B_in_cam,maskB)
  File "/opt/tiger/zyz_6d_pose/iros20-6d-pose-tracking/datasets.py", line 154, in processData
    assert (rot_label>=-1).all() and (rot_label<=1).all(),'root:\n{}\nrot_label\n{}\n A2B_in_cam_rot{}\n'.format(self.root,rot_label,A2B_in_cam_rot)
AssertionError: root:
/opt/tiger/zyz_6d_pose/iros20-6d-pose-tracking/media/YCB_traindata/ggl/train_data_blender_DR
rot_label
[ 0.5192515  -1.72661945 -0.50831636]
 A2B_in_cam_rot[[ 0.98769196  0.04075547 -0.15100854]
 [-0.04756784  0.99799397 -0.04177721]
 [ 0.14900296  0.04844617  0.98764927]]

could you give me some advice? thanks in advance.

**Comment by wenbowen123** [comment]
1. this looks correct to me, if your pkl saves the pose of B in camera (z axis forward, y axis down).
2. it looks like your generated A and B pair has too large motion. What's your setting about max_rotation?

**Comment by zhuyazhi** [comment]
thank you~
1. yes, we use the opencv camera.

2. I set the same max_rotation as yours。strangely, i found that the pose I extract from my .pkl as B_in_cam is not the same as the B_in_cam saved in .npz after running produce_train_pair_data.py.
Does there exist some transformation before saving the pose B_in_cam I extract from my .pkl  into .npz?

**Comment by wenbowen123** [comment]
The B_in_cam should be same. The original produce_train_pair_data.py may not change it. You can check where that change happens.

**Comment by zhuyazhi** [comment]
ok, thank you, i will check it.
thanks again for your kindly reply.

**Comment by zhuyazhi** [comment]
hello, wenbo，I want to know if the speed 90 fps in the paper includes the time of rendering?
I think the whole process includes render *A with the last frame's pose, crop two images as input, propagate to the se3-tracknet and get the relative pose.

**Comment by wenbowen123** [comment]
Yes, it includes all the steps.

**Comment by zhuyazhi** [comment]
thank you～

**Comment by zhuyazhi** [comment]
when doing inference， I think using the model textured_simple（1w+ faces）for rendering is suitable, is it right?
because the textured.ply includes 50w + faces, and it's time consuming when use this model to render at the last frame's pose, which can not achieve the speed reported in the paper。

**Comment by wenbowen123** [comment]
Yes, that could affect the computation time. Besides, the image to render is small (176x176) and the whole process was optimized in C++. It also depends on what hardware you are using.
