### ISSUE TITLE
请问有可用的ros版本嘛？

### ISSUE THREAD

**Issue by AGI-Mkz** [wenbowen123/iros20-6d-pose-tracking#23]
请问ROS下实现需要做些什么？希望能够得到您的答复，谢谢。

**Comment by wenbowen123** [comment]
To use it in ROS, you can write a ROS wrapper for the [tracker](https://github.com/wenbowen123/iros20-6d-pose-tracking/blob/39282d43aa06eeb6c7dca7677f6d1d73784ff610/predict.py#L127). 
I may update a ROS version some time later, though not determined when.

**Comment by wenbowen123** [comment]
Now provided.
