### ISSUE TITLE
About trans_normalizer and  rot_normalizer in datasets.py

### ISSUE THREAD

**Issue by johnbhlm** [wenbowen123/iros20-6d-pose-tracking#26]
Hi, wenbo
    In the file datasets.py , the values of trans_normalizer and  rot_normalizer , how are these two parameters set, is there any reference?

```
class TrackDataset(Dataset):
	def __init__(self, root,mode,images_mean, images_std, pretransforms=None, augmentations=None, posttransforms=None, dataset_info=None, trans_normalizer=0.03, rot_normalizer=5*np.pi/180):
```

Because when I modify the max_rotation: 15 and max_translation: 0.2 in dataset_info.yml, after generating paired data, when calling the training function to train the model,  the function of  processData() in datasets.py  throw an exception

```
 if self.mode=='train': 
             assert (trans_label<=1).all() and (trans_label>=-1).all()
             assert (rot_label >= -1).all() and (rot_label <= 1).all(),'root:\n{}\nrot_label\n{}\n A2B_in_cam_rot{}\n'.format(self. root,rot_label,A2B_in_cam_rot)
```
 
Looking forward to your reply.

**Comment by wenbowen123** [comment]
see https://github.com/wenbowen123/iros20-6d-pose-tracking/issues/22#issuecomment-791677819
