### ISSUE TITLE
about the results

### ISSUE THREAD

**Issue by zhuyazhi** [wenbowen123/iros20-6d-pose-tracking#29]
you reply is :"Not exactly. The final result is the AUC by plotting all data in a curve. For more details on this, you can refer to PoseCNN. We followed the same evaluation."

I konw this " AUC  of ADD-S"metric.
Maybe I haven't expressed my question clearly in last issue, let me tell it clearly:
1. the reported results(97.25) of "bleach cleanser'' is the  the AUC by plotting all data in a curve, I know it~;
2. but "bleach cleanser'' exists in in data_organized/0051, 0054, 0055, 0057, that is , 4 test-sets;
3. I mean, if: 
   a. AUC  of ADD-S results in 0051 is 97;
   b. AUC  of ADD-S results in 0054 is 96.5;
   c. AUC  of ADD-S results in 0055 is 97.5;
   d. AUC  of ADD-S results in 0057is 96.5;
4. then the reported results(97.25) of "bleach cleanser''  is the average of the "four AUC  of ADD-S results"?

hoping your reply~

**Comment by wenbowen123** [comment]
You can collect all videos' results and plot in a single curve. Then compute AUC from there. For more details about evaluation, you can refer to https://github.com/yuxng/PoseCNN
