### ISSUE TITLE
Bounding box format

### ISSUE THREAD

**Issue by DRM-Free** [wenbowen123/iros20-6d-pose-tracking#33]
Line 138 in predict.py , I found:
```
with_add = bounding_box / 100 * object_max_width
self.object_width = object_max_width + with_add
```
To me, it looks like object_width is supposed to be a single float. However, the bounding box is a two dimensional array (list of the 3D coordinates of the bounding box vertices) and the division makes no sense. Needless to say, with my current bounding box format, the code above won't run. What I am doing wrong ?

**Comment by wenbowen123** [comment]
bounding_box is a numpy array, so the division still works.
