### ISSUE TITLE
About the rgb map and depth map alignment

### ISSUE THREAD

**Issue by jinzhiyang1** [wenbowen123/iros20-6d-pose-tracking#35]
Hello author, thank you very much for sharing and answering. I have some problems in the process of making the data, and I hope to get your reply
1. I am also using Azure Kinect sensor to get the rgb map and depth map, but the size and scale of the two images are different. How can I manipulate the Azure Kinect sensor to get the correct rgb map and depth map and align them?
2. I noticed that the test data has "depth" and "depth_filled", is there any difference between the two files and how do I get them.

Translated with www.DeepL.com/Translator (free version)

**Comment by wenbowen123** [comment]
Hi,
1)we were using their ROS driver. For more details, please check their github page. One thing to note is check your camera's intrinsic params and see if you need to re-train.

2)The depth_filled has been filtered. If you want to test on your own camera's data, follow these steps and you just need the depth image from your camera https://github.com/wenbowen123/iros20-6d-pose-tracking#test-in-the-wild-with-ros
