### ISSUE TITLE
Blender file 1.blend does not exist

### ISSUE THREAD

**Issue by cybersonix** [wenbowen123/iros20-6d-pose-tracking#37]
Hello bowen,
     I found that the blender file 1.blend does not exist in the repository when running your code. This may cause blender_main.py cannot be run correctly. Please check and upload the file.

Thank you~
Best

**Comment by wenbowen123** [comment]
Thanks for reporting it! The readme has just been updated with the link to download.

**Comment by cybersonix** [comment]
Thanks for your reply~

**Comment by ShougangShen** [comment]
Hello  bowen, I can't download the "Blender file 1.blend". The download link appears to be invalid.

Thank you!

**Comment by wenbowen123** [comment]
@ShougangShen Hi, I just verified the link still works for me.

**Comment by ShougangShen** [comment]
Thanks for your reply.  
Sorry, I just used the link in Section ‘Data Download’ to download .
I found that the link in Section ‘Data Download’ is invalid, but the link in Section ‘Generate your own data’ can be downloaded.

**Comment by wenbowen123** [comment]
I see, thanks for reporting!

**Comment by elevenjiang1** [comment]
Sorry, but it seems that now 1.blend file can not download from Section 'Generate your own data'

**Comment by wenbowen123** [comment]
@elevenjiang1  thanks for bringing it up! Yes our server breaks recently. It should come back later this week. Stay tuned!

**Comment by wenbowen123** [comment]
@elevenjiang1 
the data should be back. Let me know if you still cannot access.

**Comment by wenbowen123** [comment]
@elevenjiang1 
should be fixed. Let me know if you still cannot access.
