### ISSUE TITLE
Call for {model}.ply files.

### ISSUE THREAD

**Issue by JiChun-Wang** [wenbowen123/iros20-6d-pose-tracking#38]
Thanks for your public code. When I run preditions on YCB and YCBInEOAT dataset, it needs .ply file of target model. However, these files seems to be in train directories which is about 15G. I would not plan to train se(3)-TrackNet networks. So could you provide a convenient link to only these .ply files for all the 21 objects?

**Comment by wenbowen123** [comment]
Hi, if you are only looking for ply files. You can download them from PoseCNN's website or YCB benchmark website. The 15G are video sequences, not including the models.

**Comment by JiChun-Wang** [comment]
There are not .ply files in PoseCNN's website and the .ply files in YCB benchmark have no rgb information for each vertex.

**Comment by wenbowen123** [comment]
Updated readme with the link to download my processed models.

**Comment by JiChun-Wang** [comment]
Thanks a lot!
