### ISSUE TITLE
Make training data set

### ISSUE THREAD

**Issue by jinzhiyang1** [wenbowen123/iros20-6d-pose-tracking#40]
Hi, can you share your method of creating a synthetic datasets?

**Comment by wenbowen123** [comment]
We recently added the guidance on this part in readme (bottom). Feel free to check it out.

**Comment by jinzhiyang1** [comment]
Thank you for your reply. I encountered a problem when I followed readme
"Please set BLENDER_PATH in bashrc！"
Does this mean I need to install blener and configure the path

**Comment by jinzhiyang1** [comment]
Can you share your blender and opencv-python versions？

**Comment by wenbowen123** [comment]
Hi, are you running inside the docker environment? Please follow the setup section in readme. The blender is 2.79. I remember the opencv version should be 4.X. You don't need to worry all these if you use docker.

**Comment by jinzhiyang1** [comment]
[](javascript:)[](javascript:void(0);)[](javascript:void(0);)[](https://fanyi.baidu.com/translate?aldtype=16047&query=&keyfrom=baidu&smartresult=dict&lang=auto2zh###)[](https://fanyi.baidu.com/translate?aldtype=16047&query=&keyfrom=baidu&smartresult=dict&lang=auto2zh###)[](javascript:void(0);)通用领域
生物医药

I didn't run in the docker environment because init system helpers > = 1.54 was missing during the installation of docker.

I run in pycharm, but it shows a syntax error. How can I deal with this.
![IMG_20220414_095456](https://user-images.githubusercontent.com/73972318/163299084-8d198f32-cb7b-4696-aa02-18203ad0d895.jpg)

**Comment by jinzhiyang1** [comment]
I didn't run in the docker environment because init system helpers > = 1.54 was missing during the installation of docker.
I run in pycharm, but it shows a syntax error. How can I deal with this error.
![IMG_20220414_095456](https://user-images.githubusercontent.com/73972318/163299206-b9d82543-6dc8-4131-ba36-101c0468587c.jpg)

**Comment by huiyang0613** [comment]
> Thank you for your reply. I encountered a problem when I followed readme "Please set BLENDER_PATH in bashrc！" Does this mean I need to install blener and configure the path

Hello, did you solve this problem, I also encountered this problem recently
