### ISSUE TITLE
关于训练时间

### ISSUE THREAD

**Issue by EnterUsernameO** [wenbowen123/iros20-6d-pose-tracking#41]
您好，温博士，请问您训练一个物体时需要多少时间？我是用3090，batch_size=200，来进行训练，发现训练200轮大概需要10天的时间，请问您在训练时需要多久的时间，我的操作是否出现了一些问题

**Comment by wenbowen123** [comment]
Hi, this doesn't sound correct. I was using 2080 Ti, batchsize 200, and training on 200k image pairs for 200 epochs take no more than 2 days. Please make sure you are indeed running on GPU not CPU.
