### ISSUE TITLE
Missing results of bleach0

### ISSUE THREAD

**Issue by WilliamKRobert** [wenbowen123/iros20-6d-pose-tracking#42]
In the prediction results ([se(3)-TrackNet's output pose estimations of YCBInEOAT](https://archive.cs.rutgers.edu/archive/a/2020/pracsys/Bowen/iros2020/YCBInEOAT_results/)), I cannot find the folder for "bleach0". Am I missing anything?

**Comment by wenbowen123** [comment]
You are right, thanks for reminding! A new link has been provided in the latest readme.

**Comment by WilliamKRobert** [comment]
Thanks!
