### ISSUE TITLE
Guide on how to use pre-trained weights

### ISSUE THREAD

**Issue by robertokcanale** [wenbowen123/iros20-6d-pose-tracking#45]
Hello, I got inside the docker container and was able to cck that the predict_ros.py runs with my rosmaster.

However, I would need a guide on how to set it up. My idea would be start using the pre-trained weights. 
Could you please provide a step-guide on:

- where is the docker mounted on my machine?
- where do I have to put the pretrianed weights and what do I need to edit?
- Any further steps before running predict_ros.py with pre-trained weights?

Many thanks for your help and support!!

**Comment by wenbowen123** [comment]
Anything (such as weights) that put under this repo's folder will be visible inside docker. You don't have to know where the docker is mounted. Just enter the docker container to access to the files under this repo's directory `/home/se3_tracknet`. Then update the path to your weights in `predict_ros.py`.
