### ISSUE TITLE
Some details about the generation of the training samples.

### ISSUE THREAD

**Issue by JiChun-Wang** [wenbowen123/iros20-6d-pose-tracking#48]
In the "Experiments" section of the paper, you said "the camera's pose is randomly sampled from a sphere of radius between 0.6 to 1.3m, followed by an additional rotation along camera z-axis sampled between 0 to 360 degree.", but it seems there is no code about the camera's pose sampling in the "blender_dataset_generator.py" file. We need your help and thank you firstly.

**Comment by Guptajakala** [comment]
Hi, this dataset generator is a later revised version. It's more related to this paper for dynamic object tracking beyond table-top scenes.
https://arxiv.org/pdf/2106.14070.pdf

**Comment by JiChun-Wang** [comment]
So If I want to track a object statically located on a table (i. e. the camera is moving, like YCB dataset), can I use the revised generator and if not, how can I change the code?

**Comment by wenbowen123** [comment]
In my previous experience, this should still work for the table-top scenario. I'd suggest to first give a try.
