### ISSUE TITLE
Epoch is not saved to the Torch checkpoint

### ISSUE THREAD

**Issue by martinlyra** [wenbowen123/iros20-6d-pose-tracking#55]
Whenever `predict_ros.py` is run with our own trained data:
```
Loading ckpt from  /home/marcusmartin/artifacts/0/model_best_val.pth.tar
Traceback (most recent call last):
  File "predict_ros.py", line 109, in <module>
    tracker = Tracker(dataset_info, images_mean, images_std,ckpt_dir,trans_normalizer=dataset_info['max_translation'],rot_normalizer=dataset_info['max_rotation'])
  File "/home/marcusmartin/iros20-tracking/predict.py", line 152, in __init__
    print('pose track ckpt epoch={}'.format(checkpoint['epoch']))
KeyError: 'epoch'
```

The culprit seems to be
https://github.com/wenbowen123/iros20-6d-pose-tracking/blob/1b63d0d16b771c4654bf9e571ede50baf7eda7a1/problems.py#L142
and
https://github.com/wenbowen123/iros20-6d-pose-tracking/blob/1b63d0d16b771c4654bf9e571ede50baf7eda7a1/problems.py#L149

Our torch version when we trained the data was `2.0.1` - if you were using an older version, may I suggest you to add a [requirements.txt](https://pip.pypa.io/en/stable/reference/requirements-file-format/) too?

**Comment by wenbowen123** [comment]
can you pull the code and retry? This issue should not be related to pytorch version. Are you running inside the docker?

**Comment by martinlyra** [comment]
Nope, we run natively on a computer that has access to the robot ROS. - The fix seems to work fine!
