### ISSUE TITLE
Unexpected keyword argument

### ISSUE THREAD

**Issue by mjnong** [wenbowen123/iros20-6d-pose-tracking#56]
https://github.com/wenbowen123/iros20-6d-pose-tracking/blob/d645214c1a06554d1389f202e842745abaa865eb/predict_ros.py#L59

https://github.com/wenbowen123/iros20-6d-pose-tracking/blob/d645214c1a06554d1389f202e842745abaa865eb/predict.py#L199

It seems as there is a mismatch between the tracker's on_track method and how it is used in `predict_ros.py`. I suggest removing the `debug_time=False` or changed the code in `predict.py` if it is intended to be used.

**Comment by wenbowen123** [comment]
thanks for reporting this! Fixed.
