### ISSUE TITLE
about predict.py path

### ISSUE THREAD

**Issue by baojun701** [wenbowen123/iros20-6d-pose-tracking#6]
hello,author.thank you first. If I want to run predict.py for test on YCBInEOAT dataset, for example banana, but I don't know how to set ycb_dir, YCBInEOAT_dir, train_data_path, ckpt_dir, mean_std_path and class id.

**Comment by wenbowen123** [comment]
there is a similar [issue ](https://github.com/wenbowen123/iros20-6d-pose-tracking/issues) to discuss this topic. Closing this for now.
