### ISSUE TITLE
clarification regarding synthetic data generation

### ISSUE THREAD

**Issue by monajalal** [wenbowen123/iros20-6d-pose-tracking#61]
I was under initial assumption that your blender file only includes bunny but I notice it includes a bunch of items inside and outside of a cube including a bunny inside the cube.

I also selected the bunny and export as ply in blender but as you see when I open it the ply in meshlab, the whole cube and objects are captured not just the bunny.

Could you please clarify what the content of 1.blend is and what we intend to do?

![Screenshot from 2023-06-05 07-37-46](https://github.com/wenbowen123/iros20-6d-pose-tracking/assets/1892917/b094cd86-6373-4389-830d-80bba8e823bd)
![Screenshot from 2023-06-05 07-37-55](https://github.com/wenbowen123/iros20-6d-pose-tracking/assets/1892917/262dec5d-a89b-4aae-bd1b-2181c7f70959)
![Screenshot from 2023-06-05 07-40-08](https://github.com/wenbowen123/iros20-6d-pose-tracking/assets/1892917/db605773-a397-4b11-bd63-0ec031a40c54)
![Screenshot from 2023-06-05 07-40-49](https://github.com/wenbowen123/iros20-6d-pose-tracking/assets/1892917/a53e560b-43b8-4046-89ec-48b99f3ab460)

**Comment by wenbowen123** [comment]
the blend file was provided for rendering the example synthetic data. In the example, the bunny is the target object, the rest are the distractor objects to augment the image background.
