### ISSUE TITLE
ValueError: could not broadcast input array from shape (226,501,3) into shape (226,0,3)

### ISSUE THREAD

**Issue by assia855** [wenbowen123/iros20-6d-pose-tracking#65]
Hi @wenbowen123, sorry for bothering you, but I don't understand how can I solve this error please. Thanks for your help.

![Screenshot from 2023-08-28 17-41-46](https://github.com/wenbowen123/iros20-6d-pose-tracking/assets/62453226/13f865ed-cf8d-4309-9908-854d476740cc)

**Comment by wenbowen123** [comment]
does this work? https://github.com/wenbowen123/iros20-6d-pose-tracking/issues/53

**Comment by wenbowen123** [comment]
I have updated the code. Please follow the new readme and see if it works.
