### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by aThinkingNeal** [wenbowen123/iros20-6d-pose-tracking#70]
Hi I am running the docker image but got this IndexError, could you take a look at it?

Thank in advance for your help!

![image](https://github.com/wenbowen123/iros20-6d-pose-tracking/assets/31988374/7a44c134-7ec2-4f2e-91f2-88009c50feda)

the content of test.sh is:

![image](https://github.com/wenbowen123/iros20-6d-pose-tracking/assets/31988374/2070ba85-3cec-4b6a-8083-883d9250ca53)

**Comment by wenbowen123** [comment]
![image](https://github.com/wenbowen123/iros20-6d-pose-tracking/assets/23078192/2d343d2b-5a58-4516-998b-6fd97a1ba11b)
from your screenshot, the dataset# is 0. This looks suspicious, can you confirm the data dir is given correctly?

**Comment by aThinkingNeal** [comment]
Thanks for your help!

Usually what should the #dataset look like?

If data dir means the --train_data_path parameter:

I have run the command "ls" on the --train_data_path parameter path, the result looks fine to me. So I guess the data dir is given correctly?

![image](https://github.com/wenbowen123/iros20-6d-pose-tracking/assets/31988374/c025a708-a1d3-455c-82af-22d319f29555)

My process of getting this data is as follows:

1. download the dataset of bleach_cleanser from this website:
https://archive.cs.rutgers.edu/archive/a/2020/pracsys/Bowen/iros2020/YCB_traindata/

2. extract it under the YCBV_data folder

---
The following point may or may not be relevant to this issue:

in the repo there is the data_organized dataset, but I have no idea on how to use it.

**Comment by wenbowen123** [comment]
https://archive.cs.rutgers.edu/archive/a/2020/pracsys/Bowen/iros2020/YCB_traindata/
this is the training data. If you want to run inference, you need to download the `data_organized` which is an organized version of YCB-Video dataset. If you have configured those correctly, expect to see `#dataset` >0

**Comment by aThinkingNeal** [comment]
![image](https://github.com/wenbowen123/iros20-6d-pose-tracking/assets/31988374/f2b84a4a-c485-4775-9ecc-a2673d9a538e)

this is my current dataset configuration, I have downloaded the `data_organized` and put them under the `ycb_dir` folder, which in my case is `/home/neal/debug/YCBV_data`.
(By the way, Could you share your dataset folder structure? It seems a bit unclear from the README session, I am afraid that others may face the same issue when setting up their dataset configuration.)

However, I am still getting the error: `IndexError: list index out of range`

![image](https://github.com/wenbowen123/iros20-6d-pose-tracking/assets/31988374/4eba1aa1-347c-452b-8ec3-38b11f0ee875)

I have tried to debug by adding a print statement in the predict.py:

![image](https://github.com/wenbowen123/iros20-6d-pose-tracking/assets/31988374/116af432-e8f2-4162-8aca-06b4b35da418)

it seems that the program didn't manage to go to the `test_data_dir` step, otherwise the print should show up in the error message.

Below is my command to run the program, note that I have updated the `ycb_dir`.

![image](https://github.com/wenbowen123/iros20-6d-pose-tracking/assets/31988374/57ee48dc-2043-4755-b6d4-592a800d658f)

**Comment by wenbowen123** [comment]
can you print `args.ycb_dir` here?
https://github.com/wenbowen123/iros20-6d-pose-tracking/blob/18dc5bac30024e4d44465f3202ba6ffbb62e8e3b/predict.py#L315

If it's not updated like what you passed in the command line, maybe it's argparse's issue. Then try to directly edit it [here](https://github.com/wenbowen123/iros20-6d-pose-tracking/blob/18dc5bac30024e4d44465f3202ba6ffbb62e8e3b/predict.py#L631)

**Comment by aThinkingNeal** [comment]
Thanks for the help, I have managed to solve the `IndexError` problem. 
Essentially it is the `test_data_path` is not correctly configured.

Here is what I changed to make it work:

## First step: 
change the line of code from [here](https://github.com/wenbowen123/iros20-6d-pose-tracking/blob/18dc5bac30024e4d44465f3202ba6ffbb62e8e3b/predict.py#L450)

to 

`test_data_path = '{}/data_organized/%04d'.format(args.ycb_dir)%(seq_id)`

## Second Step:

organized my dataset configuration as:

`/home/neal/debug/YCBV_data/data_organized/0051`

In this way the test dataset is correctly passed and the problem is solved

I think the confusion comes from the README and codebase mismatch:

Here in the README session implies that should be a `data_organized` folder

![image](https://github.com/wenbowen123/iros20-6d-pose-tracking/assets/31988374/1c413310-1ec2-4bb9-8ae4-2c83f445b96c)

However in the codebase this folder path is not reflected.

Hope this helps!
