### ISSUE TITLE
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.

### ISSUE THREAD

**Issue by ZisongXu** [wenbowen123/iros20-6d-pose-tracking#76]
Hi Dear Bowen:

I am coming from your another repository "BundleSDF", and you recommend me to use "se3-tracknet".

I am trying re-run your code but I got this issue:
`
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.`

Because our lab uses the singularity container, I would like to reproduce your project in singularity first. When I built the singularity container, I changed the image to the docker image you provided and it seemed that the build was successful. But when I run your example code it had the above problem.

I am thinking that my GPU is 4090, could it be that the version of cuda and cudnn is too low, causing the GPU to be unable to be used? Because after I created the container, I found that it was ubuntu16 and the cuda version was 10.1.

If your code supports GPU4090, maybe I should use docker containers. But I just wanted to try singularity first.

Best Regards
Zisong Xu

**Comment by wenbowen123** [comment]
@ZisongXu, I'm not familiar with singularity. It might worth checking [here](https://github.com/wenbowen123/iros20-6d-pose-tracking/blob/18dc5bac30024e4d44465f3202ba6ffbb62e8e3b/docker/dockerfile#L1) and revise the cuda version that matches your GPU. Then rebuild the docker image.

Also, I'd recommend to take a look at our recent work [FoundationPose](https://github.com/NVlabs/FoundationPose), which does not need per-object training and can be immediately applied to novel objects.

**Comment by ZisongXu** [comment]
@wenbowen123 Ok thanks a lot!!! Can I ask when will you upload the code of [FoundationPose](https://github.com/NVlabs/FoundationPose), I realized that I can see the paper on arXiv.

**Comment by ZisongXu** [comment]
@wenbowen123  Oh sorry, by the way do I also need to change the version of Ubuntu from 16 to 20?

**Comment by wenbowen123** [comment]
Our target release is in March/April.

Re Ubuntu version, I haven't tried that. If you run into dependency issues that expect certain OS version, might worth changing that too.

**Comment by ZisongXu** [comment]
Thanks a lot!

**Comment by wenbowen123** [comment]
@ZisongXu Our FoundationPose code has released.
