### ISSUE TITLE
SET UP PROBLEM

### ISSUE THREAD

**Issue by Hitlzw** [wenbowen123/iros20-6d-pose-tracking#81]
![2024-03-12 19-34-42屏幕截图](https://github.com/wenbowen123/iros20-6d-pose-tracking/assets/126162710/481a4459-ce22-4967-bd4b-d05d299744c5)
what is the problem?Should I install nvidia-docker?

**Comment by wenbowen123** [comment]
yes, have you tried that?

**Comment by Hitlzw** [comment]
> yes, have you tried that?

Thank you, professor, at the moment I have been able to run the code locally without any problems. But I wonder how much GPU memory the model will use.Only 246MiB?
![2024-03-14 16-04-13屏幕截图](https://github.com/wenbowen123/iros20-6d-pose-tracking/assets/126162710/751ac05e-c119-4a34-927d-58e362181ec8)

**Comment by wenbowen123** [comment]
I dont remember the exact memory usage. But it is indeed a light-weight network and consumes less memory. Closing since the issue has been resolved.
