### ISSUE TITLE
Tracking object in real-time

### ISSUE THREAD

**Issue by ChenxMa** [wenbowen123/iros20-6d-pose-tracking#82]
Hi,

Thanks for your excellent work, I'm trying to track the object pose in real-time,  just like your paper: Vision-driven Compliant Manipulation for Reliable, High-Precision Assembly Tasks. In the paper you mentioned:

> The initial 6D pose of each object on the support surface is estimated once via RANSAC-based plane fitting and removal, followed by a single-shot pose estimation approach  to initialize tracking

I realized that the initial point is important in real-time tracking. In [#57 ](https://github.com/wenbowen123/iros20-6d-pose-tracking/issues/57#issuecomment-1555045148) you mentioned an offline annotator. So if you please give me some advice about how to get an online initial pose estimator, like how to use  "RANSAC-based plane fitting and removal and a single-shot pose estimation approach to initialize tracking" or other methods?

Thanks in advance!

**Comment by wenbowen123** [comment]
@ChenxMa back then we used a heuristics-based method like you pointed out. But I'd encourage you to check our recent work [FoundationPose](https://github.com/NVlabs/FoundationPose) which serves this purpose perfectly.

**Comment by ChenxMa** [comment]
Thanks for your early reply, I will read the paper carefully, and please let me know if the code is released
