### ISSUE TITLE
generate data problem

### ISSUE THREAD

**Issue by Hitlzw** [wenbowen123/iros20-6d-pose-tracking#83]
When I run the python blender_main.py command, I can generate data normally when I don't modify dataset_info.yml. But when I changed focalX, focalY, centerX, centerY in dataset_info.yml to the parameters of my real-world camera, the resulting data got weird. The resolution of a real-world camera is also 640x480.
![2024-03-19 20-46-38屏幕截图](https://github.com/wenbowen123/iros20-6d-pose-tracking/assets/126162710/e7e9ac82-b177-4e1d-89df-3ee2e7edc2c0)
![0000002rgb](https://github.com/wenbowen123/iros20-6d-pose-tracking/assets/126162710/158653c8-8da3-43f4-8350-87f19cda0604)
![0000002seg](https://github.com/wenbowen123/iros20-6d-pose-tracking/assets/126162710/08ec5fed-a5b0-4d22-bc01-10bd206f20e2)

**Comment by wenbowen123** [comment]
Hi, it has been a long time since I worked on this part. I'd encourage to checkout our recent work [FoundationPose](https://github.com/NVlabs/FoundationPose) which can be immediately applied to your setup without retraining.

**Comment by Hitlzw** [comment]
Thank you for your reply. I think the cause of the problem is that the newly set camera parameters caused the camera FOV to become larger, and the camera FOV exceeded the scope of the box in 1.blender file (I don't know much about blender operation), which caused the rgb graphics and seg images to become abnormal. And I've been watching FoundationPose for a while, looking forward to its code.
![QQ图片20240320104923](https://github.com/wenbowen123/iros20-6d-pose-tracking/assets/126162710/8602931b-3d08-4e53-ac2a-eff4cf4cf346)

**Comment by Hitlzw** [comment]
> Hi, it has been a long time since I worked on this part. I'd encourage to checkout our recent work [FoundationPose](https://github.com/NVlabs/FoundationPose) which can be immediately applied to your setup without retraining.

Thank you for your reply.  I think the cause of the problem is that the newly set camera parameters caused the camera FOV to become larger, and the camera FOV exceeded the scope of the box in 1. blender file (I don't know much about blender operation), which caused the rgb graphics and seg images to become abnormal.  And I've been watching FoundationPose for a while, looking forward to its code.
![314365485-8602931b-3d08-4e53-ac2a-eff4cf4cf346](https://github.com/wenbowen123/iros20-6d-pose-tracking/assets/126162710/bd4c4433-fa8f-4754-931a-e5585c467a5c)
